print("New Hello Git")
print("Avazo un poco el codigo que tengo pendiente")
print("Nueva linea para actualizar")
print("Segunda linea para actualizar")
print("Vamos mejorando un poco más el codigo")
print("Editamos el codigo nuevamente")